import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,writeFile,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join,resolve} from 'node:path'
import {createHash} from 'node:crypto'
import {refreshStudioCapabilities,observeStudioAudio,checkStudioSpeech} from '../src/studio-host.ts'
import {fileSha256} from '../src/studio-tools.ts'
async function setup(t:any){const cwd=await mkdtemp(join(tmpdir(),'studio-host-test-'));t.after(()=>rm(cwd,{recursive:true,force:true}));const path=join(cwd,'asset'),proofPath=join(cwd,'proof.json');await writeFile(path,'asset');await writeFile(proofPath,'{}');const sha256=await fileSha256(path),task={id:cwd,cwd,design:{studio:{referenceSha256:sha256,characterId:'c'}}},records:any[]=[],workflow:any={recordCapability:(_:any,v:any)=>records.push(v)};return {cwd,path,sha256,task,records,workflow,proofPath}}
test('actual dependency proofs map HyperFrames, freeze reference and character paths',async t=>{const s=await setup(t),p={ok:true,path:s.path,sha256:s.sha256,proofPath:s.proofPath};let calls=0;const opts={config:{preflightScript:'fake'},execute:async()=>{calls++;return {capabilities:{reference:p,frames:p,hyperframes:{...p,hyperframes_verified:true,scope:'actual_hyperframes_smoke_render'},character:{...p,characterId:'c',imagePath:s.path,imageSha256:s.sha256,profilePath:s.path,profileAssetId:'profile'}}}}};const result=await refreshStudioCapabilities(s.workflow,s.task,opts);assert.equal(result.reference.sha256,s.sha256);assert.equal(result.characterReferences[0].id,'profile');assert.equal(s.records.find(v=>v.name==='render').status,'passed');await refreshStudioCapabilities(s.workflow,s.task,opts);assert.equal(calls,1);await writeFile(s.path,'tampered');s.records.length=0;await refreshStudioCapabilities(s.workflow,s.task,opts);assert.equal(s.records.find(v=>v.name==='reference').status,'failed')})
test('FFmpeg-only smoke never satisfies HyperFrames render capability',async t=>{const s=await setup(t);await refreshStudioCapabilities(s.workflow,s.task,{config:{preflightScript:'fake'},execute:async()=>({capabilities:{render:{ok:true,path:s.path,sha256:s.sha256,proofPath:s.proofPath}}})});assert.equal(s.records.find(v=>v.name==='render').status,'failed')})
test('actual saved calibration grants bounded capability, explicitly no performance approval',async t=>{const s=await setup(t);await refreshStudioCapabilities(s.workflow,s.task,{config:{calibrationPath:resolve('../autonomous-studio/evidence/speech-calibration.json'),audioScript:'script',vaultTokenFile:'file'}});const r=s.records.find(v=>v.name==='audio_calibration');assert.equal(r.status,'passed');assert.match(r.reason,/performance_calibrated=false/);assert.match(r.reason,/retrospective/);assert.equal(s.records.find(v=>v.name==='audio').status,'passed')})
test('audio host rejects wrong digest and accepts genuine complete observation',async t=>{const s=await setup(t),args={wavPath:s.path,start:0,end:1},config={audioScript:'audio',vaultTokenFile:'file'};await assert.rejects(observeStudioAudio(s.task,args,{config,execute:async()=>({ok:true,input_modality:'input_audio',finish_reason:'stop',audio_sha256:'wrong'})}),/invalid/);const r=await observeStudioAudio(s.task,args,{config,execute:async()=>({ok:true,input_modality:'input_audio',finish_reason:'stop',audio_sha256:s.sha256})});assert.equal(r.audio_sha256,s.sha256)})
test('speech host accepts blocked content as evidence, never treats it as execution failure',async t=>{const s=await setup(t),args={wavPath:s.path,start:0,end:1,expectedText:'你好',stage:'final' as const},config={speechScript:'speech',vaultTokenFile:'file'};const result=await checkStudioSpeech(s.task,args,{config,execute:async()=>({ok:true,audio_sha256:s.sha256,expected_text_sha256:createHash('sha256').update('你好').digest('hex'),content_gate:'blocked'})});assert.equal(result.content_gate,'blocked')})
test('audio failure reports safe stage and HTTP code without secrets or provider body',async t=>{const s=await setup(t),args={wavPath:s.path,start:0,end:1},config={audioScript:'audio',vaultTokenFile:'file'};await assert.rejects(observeStudioAudio(s.task,args,{config,execute:async()=>({ok:false,error_stage:'vault',error_type:'HTTPError',http_status:403,body:'secret'})}),{message:'studio-audio-failed:vault:HTTPError-http-403'});await assert.rejects(observeStudioAudio(s.task,args,{config,execute:async()=>({ok:false,error_stage:'secret',error_type:'secret',http_status:'token'})}),{message:'studio-audio-failed:unknown:Error'})})
