/** Spoken-text evidence is separate from performance/mix approval. All identities and audio paths are host-derived. */
import {readFile,realpath,mkdir,mkdtemp,stat} from 'node:fs/promises'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import {studioPath,fileSha256} from './studio-tools.js'
const run=promisify(execFile),sha=(v:string)=>createHash('sha256').update(v).digest('hex')
export const STUDIO_SPEECH_TOOL_NAMES=['studio_freeze_script','studio_register_speech_plan','studio_check_speech'] as const
export interface StudioSpeechOptions {input:any;workflow:any;isActive:()=>boolean;speechCheck:(v:{wavPath:string;start:number;end:number;expectedText:string;stage:'source'|'final'})=>Promise<any>;runCommand?:(file:string,args:string[])=>Promise<{stdout:string}>}
export async function registerStudioSpeechTools(ctx:any,o:StudioSpeechOptions){
 const {input,workflow}=o,role=input.card?.role,disposers:(()=>void)[]=[]
 const defineTool=process.env.NODE_ENV==='test'?(v:any)=>v:(await import('@deepseek-ai/dsh-tools')).defineTool
 const command=o.runCommand??((file,args)=>run(file,args,{timeout:60000,maxBuffer:1024*1024}).then(r=>({stdout:String(r.stdout)})))
 const check=(e?:any)=>{if(!o.isActive())throw Error('studio-stale-run');if(e?.agent?.session?.id&&e.agent.session.id!==input.sessionId)throw Error('studio-session-mismatch')}
 const requireRole=(r:string)=>{if(role!==r)throw Error('studio-role-denied')}
 const register=(name:string,description:string,parameters:any,f:(a:any)=>Promise<any>)=>disposers.push(ctx.tools.register(defineTool({name,description,parameters,output:{schema:{type:'object',additionalProperties:true},render:(_:any,v:any)=>[{type:'text',text:JSON.stringify(v)}]},execute:async(a:any,e:any)=>{check(e);return JSON.parse(JSON.stringify(await f(a)))}})))
 const candidate=async()=>{const saved=workflow.status(input).candidate,c=saved?.candidate??saved,l=workflow.candidateLocation(input);if(!c||!l)throw Error('studio-candidate-required');const path=await studioPath(input.task.cwd,l.path);if(await fileSha256(path)!==c.sha256)throw Error('studio-candidate-file-changed');check();return {c,path}}
 const lines=(v:any)=>{if(!Array.isArray(v)||!v.length||v.length>300)throw Error('studio-script-invalid');const ids=new Set();return v.map((l:any)=>{if(!l||typeof l.id!=='string'||!l.id||l.id.length>100||ids.has(l.id)||typeof l.text!=='string'||!l.text.trim()||l.text.length>2000)throw Error('studio-script-invalid');ids.add(l.id);return {id:l.id,text:l.text}})}
 register('studio_freeze_script','Planner only: freeze original dialogue before synthesis. Producer speech plan must exactly preserve ids and text.',{lines:{type:'array',required:true,items:{type:'object',additionalProperties:true}}},async a=>{requireRole('planner');const value=lines(a.lines),script={sha256:sha(JSON.stringify(value)),lines:value};check();workflow.recordScript(input,script);return script})
 register('studio_register_speech_plan','Producer only: register timed dialogue JSON array for the current MP4, matching frozen script exactly. Each source clip and final span must be at most 8 seconds.',{path:{type:'string',required:true}},async a=>{
  requireRole('executor');const {c,path:film}=await candidate(),path=await studioPath(input.task.cwd,a.path,true);if((await stat(path)).size>1024*1024)throw Error('studio-speech-plan-too-large');const raw=JSON.parse(await readFile(path,'utf8')),simple=lines(raw),script=workflow.script(input);if(!script||JSON.stringify(simple)!==JSON.stringify(script.lines))throw Error('studio-speech-script-mismatch');const result:any[]=[];let previousEnd=0
  for(const l of raw){if(!Number.isFinite(l.start)||!Number.isFinite(l.end)||l.start<previousEnd||l.end<=l.start||l.end>c.durationSeconds||l.end-l.start>8)throw Error('studio-speech-range-invalid');previousEnd=l.end;const sourcePath=await studioPath(input.task.cwd,l.sourcePath),sourceSha256=await fileSha256(sourcePath),probe=JSON.parse((await command(process.env.FFPROBE_PATH??'ffprobe',['-v','error','-show_streams','-show_format','-of','json',sourcePath])).stdout),sourceDurationSeconds=Number(probe.format?.duration);if(!probe.streams?.some((s:any)=>s.codec_type==='audio')||!Number.isFinite(sourceDurationSeconds)||sourceDurationSeconds<=0||sourceDurationSeconds>8)throw Error('studio-source-audio-invalid');if(await fileSha256(sourcePath)!==sourceSha256)throw Error('studio-source-file-changed');result.push({id:l.id,text:l.text,start:l.start,end:l.end,sourcePath,sourceSha256,sourceDurationSeconds})}
  if(await fileSha256(film)!==c.sha256)throw Error('studio-candidate-file-changed');check();const plan={candidateSha256:c.sha256,scriptSha256:script.sha256,planSha256:sha(JSON.stringify(result)),lines:result};workflow.recordSpeechPlan(input,plan);return {candidateSha256:plan.candidateSha256,planSha256:plan.planSha256,scriptSha256:plan.scriptSha256,lineCount:result.length,qualityApproved:false}
 })
 register('studio_check_speech','Independent reviewer: check one frozen line in original source or final MP4. Text coverage is not performance or mix approval.',{lineId:{type:'string',required:true},stage:{type:'string',required:true,enum:['source','final']}},async a=>{
  requireRole('reviewer');if(a.stage!=='source'&&a.stage!=='final')throw Error('studio-speech-stage-invalid');const {c,path}=await candidate(),plan=workflow.speechPlan(input);if(!plan||plan.candidateSha256!==c.sha256)throw Error('studio-speech-plan-stale');const line=plan.lines.find((l:any)=>l.id===a.lineId);if(!line)throw Error('studio-speech-line-required');const source=a.stage==='source'?await studioPath(input.task.cwd,line.sourcePath):path,expectedSha=a.stage==='source'?line.sourceSha256:c.sha256;if(await fileSha256(source)!==expectedSha)throw Error('studio-source-file-changed');const start=a.stage==='source'?0:line.start,end=a.stage==='source'?line.sourceDurationSeconds:line.end;if(end-start>8||end<=start)throw Error('studio-speech-range-invalid');const root=await realpath(input.task.cwd),base=join(root,'.studio-review');await mkdir(base,{recursive:true,mode:0o700});if(await realpath(base)!==base)throw Error('studio-review-directory-symlink');const wavPath=join(await mkdtemp(join(base,'speech-')),'audio.wav');await command(process.env.FFMPEG_PATH??'ffmpeg',['-nostdin','-v','error','-ss',String(start),'-i',source,'-t',String(end-start),'-vn','-ac','1','-ar','16000','-c:a','pcm_s16le','-y',wavPath]);const audioSha256=await fileSha256(wavPath);check();const result=await o.speechCheck({wavPath,start,end,expectedText:line.text,stage:a.stage});if(!result||result.error||result.isError||result.ok!==true||result.observation?.input_modality!=='input_audio'||result.observation?.finish_reason!=='stop'||result.observation?.audio_sha256!==audioSha256||result.audio_sha256!==audioSha256||result.expected_text_sha256!==sha(line.text)||!['pass','blocked'].includes(result.content_gate))throw Error('studio-speech-observation-invalid');if(await fileSha256(wavPath)!==audioSha256||await fileSha256(source)!==expectedSha||await fileSha256(path)!==c.sha256)throw Error('studio-source-file-changed');check();const latest=workflow.speechPlan(input);if(latest?.planSha256!==plan.planSha256||latest?.candidateSha256!==c.sha256)throw Error('studio-speech-plan-stale');const record={candidateSha256:c.sha256,planSha256:plan.planSha256,lineId:line.id,stage:a.stage,audioSha256,start,end,result};const receipt=workflow.recordSpeechCheck(input,record);return {...record,receipt,qualityApproved:false,scope:'speech-content-only; no performance or mix approval'}
 })
 return ()=>{for(const d of disposers.splice(0))d()}
}
