import {STUDIO_SPEECH_MAX_SECONDS} from './studio-speech-limits.js'
/** Spoken-text evidence is separate from performance/mix approval. All identities and audio paths are host-derived. */
import {readFile,realpath,mkdir,mkdtemp,stat} from 'node:fs/promises'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import {studioPath,fileSha256} from './studio-tools.js'
const run=promisify(execFile),sha=(v:string)=>createHash('sha256').update(v).digest('hex')
export const STUDIO_SPEECH_TOOL_NAMES=['studio_probe_audio_sources','studio_freeze_script','studio_register_speech_plan','studio_check_speech'] as const
export interface StudioSpeechOptions {input:any;workflow:any;isActive:()=>boolean;speechCheck:(v:{wavPath:string;start:number;end:number;expectedText:string;stage:'source'|'final'})=>Promise<any>;runCommand?:(file:string,args:string[])=>Promise<{stdout:string}>}
export async function registerStudioSpeechTools(ctx:any,o:StudioSpeechOptions){
 const {input,workflow}=o,role=input.card?.role,disposers:(()=>void)[]=[]
 // Compile with the real host DSL in tests too: JSON Schema keywords are not
 // necessarily accepted by DSH's authoring format.
 const {defineTool}=await import('@deepseek-ai/dsh-tools')
 const command=o.runCommand??((file,args)=>run(file,args,{timeout:60000,maxBuffer:1024*1024}).then(r=>({stdout:String(r.stdout)})))
 const check=(e?:any)=>{if(!o.isActive())throw Error('studio-stale-run');if(e?.agent?.session?.id&&e.agent.session.id!==input.sessionId)throw Error('studio-session-mismatch')}
 const requireRole=(r:string)=>{if(role!==r)throw Error('studio-role-denied')}
 const register=(name:string,description:string,parameters:any,f:(a:any)=>Promise<any>)=>disposers.push(ctx.tools.register(defineTool({name,description,parameters,output:{schema:{type:'object',additionalProperties:true},render:(_:any,v:any)=>[{type:'text',text:JSON.stringify(v)}]},execute:async(a:any,e:any)=>{check(e);const result=await f(a);return JSON.parse(JSON.stringify(role==='reviewer'&&name==='studio_check_speech'?{...result,reviewProgress:workflow.reviewProgress?.(input)??null}:result))}})))
 const candidate=async()=>{const saved=workflow.status(input).candidate,c=saved?.candidate??saved,l=workflow.candidateLocation(input);if(!c||!l)throw Error('studio-candidate-required');const path=await studioPath(input.task.cwd,l.path);if(await fileSha256(path)!==c.sha256)throw Error('studio-candidate-file-changed');check();return {c,path}}
 const lines=(v:any)=>{if(!Array.isArray(v)||!v.length||v.length>300)throw Error('studio-script-invalid');const ids=new Set();return v.map((l:any)=>{if(!l||typeof l.id!=='string'||!l.id||l.id.length>100||ids.has(l.id)||typeof l.text!=='string'||!l.text.trim()||l.text.length>2000)throw Error('studio-script-invalid');ids.add(l.id);return {id:l.id,text:l.text}})}
 // Keep the 80-source bound in audioSources; maxItems is not in the DSH DSL.
 const sourcesParameter={type:'array',items:{type:'object',properties:{id:{type:'string',required:true},path:{type:'string',required:true}},additionalProperties:false}}
 const audioSources=(v:any)=>{if(!Array.isArray(v)||!v.length||v.length>80)throw Error('studio-audio-sources-invalid');const ids=new Set();return v.map((source:any)=>{if(!source||typeof source.id!=='string'||!source.id||source.id.length>100||ids.has(source.id)||typeof source.path!=='string'||!source.path.trim())throw Error('studio-audio-sources-invalid');ids.add(source.id);return {id:source.id,path:source.path}})}
 const probeSources=async(sources:{id:string;path:string}[])=>{
  const durationMax=input.task.design?.studio?.durationMax
  if(typeof durationMax!=='number'||!Number.isFinite(durationMax)||durationMax<=0)throw Error('studio-duration-max-required')
  const result:{id:string;path:string;sha256:string;durationSeconds:number}[]=[]
  for(const source of sources){check();const path=await studioPath(input.task.cwd,source.path),digest=await fileSha256(path);check();const probe=JSON.parse((await command(process.env.FFPROBE_PATH??'ffprobe',['-v','error','-show_streams','-show_format','-of','json',path])).stdout),durationSeconds=Number(probe.format?.duration);check();if(!probe.streams?.some((s:any)=>s.codec_type==='audio')||!Number.isFinite(durationSeconds)||durationSeconds<=0)throw Error('studio-source-audio-invalid');if(await fileSha256(path)!==digest)throw Error('studio-source-file-changed');result.push({id:source.id,path,sha256:digest,durationSeconds})}
  // Recheck the whole set: probing later clips must not allow earlier inputs to change.
  for(const source of result){if(await fileSha256(source.path)!==source.sha256)throw Error('studio-source-file-changed');check()}
  const totalDurationSeconds=result.reduce((sum,source)=>sum+source.durationSeconds,0)
  if(!Number.isFinite(totalDurationSeconds))throw Error('studio-source-audio-invalid')
  return {sources:result,totalDurationSeconds,durationMax,fits:totalDurationSeconds<=durationMax,qualityApproved:false,scope:'source-duration-only; no performance, pacing or mix approval'}
 }
 register('studio_probe_audio_sources','Read-only for planner, producer or reviewer: hash and probe actual project audio clips, returning summed source duration against the task durationMax. This is a technical duration check, not quality approval.',{sources:{...sourcesParameter,required:true}},async a=>{if(!['planner','executor','reviewer','studio-stage'].includes(role))throw Error('studio-role-denied');return probeSources(audioSources(a.sources))})
 register('studio_freeze_script','Planner only: freeze complete spoken dialogue as lines=[{id,text}] before synthesis. text contains only words to say; leading text-bearing bracket annotations are ambiguous and rejected. Put non-spoken action, sound and delivery notes in storyboard/performance notes linked by line id, not TTS text. If an annotation was meant as speech, the director must explicitly rephrase it as dialogue; never silently strip words or change old frozen text downstream. This is not an emotion API and does not prove expressive delivery. Respect the task dialogueLanguage (zh-CN means natural Chinese dialogue; do not synthesize English direction notes). After an independent major/blocker review bound to the current candidate, the planner may revise and refreeze dialogue for repair; freezing is not a permanent ban on fixing an underdeveloped story. Downstream stages must use the revised exact lines and original remaining generation budget. Optional sources must match line ids in order; sources are required when voice generation budget is zero, and their actual total must fit durationMax.',{lines:{type:'array',required:true,items:{type:'object',additionalProperties:true}},sources:sourcesParameter},async a=>{
  requireRole('planner');const value=lines(a.lines);let audio:Pick<Awaited<ReturnType<typeof probeSources>>,'sources'|'totalDurationSeconds'>|undefined
  if(a.sources===undefined&&input.task.design?.studio?.generationLimits?.voiceSegments===0)throw Error('studio-script-audio-sources-required')
  if(a.sources!==undefined){const sources=audioSources(a.sources);if(sources.length!==value.length||sources.some((source,i)=>source.id!==value[i].id))throw Error('studio-script-audio-sources-mismatch');const probe=await probeSources(sources);if(!probe.fits)throw Error('studio-script-audio-duration-exceeds-max');audio={sources:probe.sources,totalDurationSeconds:probe.totalDurationSeconds}}
  const script={sha256:sha(JSON.stringify(value)),lines:value,...audio};check();workflow.recordScript(input,script);return script
 })
 register('studio_register_speech_plan',`Producer only: register a JSON root array of {id,text,start,end,sourcePath} for the current MP4, matching frozen script exactly. Not a sound-plan wrapper or source manifest. A successful structured compile emits speech-plan.json inside its composition directory: read and reuse it if it matches this candidate rather than retyping times. Each source clip and final span must be at most ${STUDIO_SPEECH_MAX_SECONDS} seconds. Preserve the manifest file already bound to the candidate.`,{path:{type:'string',required:true}},async a=>{
  requireRole('executor');const {c,path:film}=await candidate(),path=await studioPath(input.task.cwd,a.path,true);if((await stat(path)).size>1024*1024)throw Error('studio-speech-plan-too-large');const raw=JSON.parse(await readFile(path,'utf8'))
  if(!Array.isArray(raw))throw Error('studio-speech-plan-array-required: '+JSON.stringify({
   error_code:'studio-speech-plan-array-required',field:'root',requiredItemFields:['id','text','start','end','sourcePath'],registered:false,
   action:'Use a JSON root array of timed lines, not a planning wrapper with version/dialogue/lines. Read the speech-plan.json emitted inside the successful composition directory and use it if it matches this candidate. Do not overwrite the source manifest already bound to a registered candidate.',
  }))
  for(let i=0;i<raw.length;i++){
   const l=raw[i],missing=['id','text','start','end','sourcePath'].filter(k=>!l||typeof l!=='object'||!(k in l))
   if(missing.length)throw Error('studio-speech-plan-fields-required: '+JSON.stringify({error_code:'studio-speech-plan-fields-required',field:`lines[${i}]`,missing,registered:false,action:'Use id/text from the exact frozen script; start/end are final-film seconds and sourcePath is the actual project audio path. Reuse the compiler-generated speech-plan when it belongs to this candidate.'}))
  }
  const simple=lines(raw),script=workflow.script(input);if(!script||JSON.stringify(simple)!==JSON.stringify(script.lines))throw Error('studio-speech-script-mismatch');const result:any[]=[];let previousEnd=0
  for(const l of raw){if(!Number.isFinite(l.start)||!Number.isFinite(l.end)||l.start<0||l.start<previousEnd-1e-9||l.end<=l.start||l.end>c.durationSeconds+1e-9||l.end-l.start>STUDIO_SPEECH_MAX_SECONDS+1e-9)throw Error('studio-speech-range-invalid');previousEnd=l.end;const sourcePath=await studioPath(input.task.cwd,l.sourcePath),sourceSha256=await fileSha256(sourcePath),probe=JSON.parse((await command(process.env.FFPROBE_PATH??'ffprobe',['-v','error','-show_streams','-show_format','-of','json',sourcePath])).stdout),sourceDurationSeconds=Number(probe.format?.duration);if(!probe.streams?.some((s:any)=>s.codec_type==='audio')||!Number.isFinite(sourceDurationSeconds)||sourceDurationSeconds<=0||sourceDurationSeconds>STUDIO_SPEECH_MAX_SECONDS)throw Error('studio-source-audio-invalid');if(await fileSha256(sourcePath)!==sourceSha256)throw Error('studio-source-file-changed');result.push({id:l.id,text:l.text,start:l.start,end:l.end,sourcePath,sourceSha256,sourceDurationSeconds})}
  if(await fileSha256(film)!==c.sha256)throw Error('studio-candidate-file-changed');check();const plan={candidateSha256:c.sha256,scriptSha256:script.sha256,planSha256:sha(JSON.stringify(result)),lines:result};workflow.recordSpeechPlan(input,plan);return {candidateSha256:plan.candidateSha256,planSha256:plan.planSha256,scriptSha256:plan.scriptSha256,lineCount:result.length,qualityApproved:false}
 })
 register('studio_check_speech','Independent reviewer: check one frozen line in original source or final MP4. Use result.content_gate and normalized-word issues for missing/wrong words; punctuation and whitespace are not spoken words. A transcript without an exclamation mark is not missing speech or proof of weak emotion. Assess delivery from actual audio separately. Text coverage is not performance or mix approval.',{lineId:{type:'string',required:true},stage:{type:'string',required:true,enum:['source','final']}},async a=>{
  requireRole('reviewer');if(a.stage!=='source'&&a.stage!=='final')throw Error('studio-speech-stage-invalid');const {c,path}=await candidate(),plan=workflow.speechPlan(input);if(!plan||plan.candidateSha256!==c.sha256)throw Error('studio-speech-plan-stale');const line=plan.lines.find((l:any)=>l.id===a.lineId);if(!line)throw Error('studio-speech-line-required');const source=a.stage==='source'?await studioPath(input.task.cwd,line.sourcePath):path,expectedSha=a.stage==='source'?line.sourceSha256:c.sha256;if(await fileSha256(source)!==expectedSha)throw Error('studio-source-file-changed');const start=a.stage==='source'?0:line.start,end=a.stage==='source'?line.sourceDurationSeconds:line.end;if(end-start>STUDIO_SPEECH_MAX_SECONDS+1e-9||end<=start)throw Error('studio-speech-range-invalid');const root=await realpath(input.task.cwd),base=join(root,'.studio-review');await mkdir(base,{recursive:true,mode:0o700});if(await realpath(base)!==base)throw Error('studio-review-directory-symlink');const wavPath=join(await mkdtemp(join(base,'speech-')),'audio.wav');await command(process.env.FFMPEG_PATH??'ffmpeg',['-nostdin','-v','error','-ss',String(start),'-i',source,'-t',String(end-start),'-vn','-ac','1','-ar','16000','-c:a','pcm_s16le','-y',wavPath]);const audioSha256=await fileSha256(wavPath);check();const result=await o.speechCheck({wavPath,start,end,expectedText:line.text,stage:a.stage});if(!result||result.error||result.isError||result.ok!==true||result.observation?.input_modality!=='input_audio'||result.observation?.finish_reason!=='stop'||result.observation?.audio_sha256!==audioSha256||result.audio_sha256!==audioSha256||result.expected_text_sha256!==sha(line.text)||!['pass','blocked'].includes(result.content_gate))throw Error('studio-speech-observation-invalid');if(await fileSha256(wavPath)!==audioSha256||await fileSha256(source)!==expectedSha||await fileSha256(path)!==c.sha256)throw Error('studio-source-file-changed');check();const latest=workflow.speechPlan(input);if(latest?.planSha256!==plan.planSha256||latest?.candidateSha256!==c.sha256)throw Error('studio-speech-plan-stale');const record={candidateSha256:c.sha256,planSha256:plan.planSha256,lineId:line.id,stage:a.stage,audioSha256,start,end,result};const receipt=workflow.recordSpeechCheck(input,record);return {...record,receipt,qualityApproved:false,scope:'Normalized spoken-word coverage only: punctuation differences are not missing speech. content_gate=pass does not approve delivery, emotion or mix; evaluate actual audio separately.'}
 })
 return ()=>{for(const d of disposers.splice(0))d()}
}
